const elements = [
  { data: { id: "weather", label: "Weather", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "wine", label: "Wine", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "word", label: "Word", nodeType: "parent" }, classes: "main" }, //done
  { data: { id: "time", label: "Time", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "email", label: "Email", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "image", label: "Image", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "parking", label: "Parking", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "money", label: "Money", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "payment", label: "Payment", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "flight_booking", label: "FlightBooking", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "rating", label: "Rating", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "recipe", label: "Recipe", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "person", label: "Person", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "calendar", label: "Calendar", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "authorization", label: "Authorization", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "residence", label: "Residence", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "comic_strip", label: "comicStrip", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "measurement", label: "Measurement", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "earthquake", label: "Earthquake", nodeType: "parent" }, classes: "main" }, // done
  { data: { id: "restaurant", label: "Restaurant", nodeType: "parent" }, classes: "main" }, // done

  // Linking overlapping modules
//   { data: { source: "calendar", target: "time" } },
//   { data: { source: "calendar", target: "email" } },
//   { data: { source: "authorization", target: "person" } },
//   { data: { source: "residence", target: "person" } },
//   { data: { source: "payment", target: "money" } },
//   { data: { source: "flight_booking", target: "payment" } },
//   { data: { source: "rating", target: "recipe" } },
//   { data: { source: "rating", target: "person" } },
//   { data: { source: "word", target: "email" } },
//   { data: { source: "word", target: "time" } },
//   { data: { source: "image", target: "email" } },
//   { data: { source: "image", target: "word" } },
//   { data: { source: "weather", target: "time" } },
//   { data: { source: "wine", target: "recipe" } },
//   { data: { source: "wine", target: "rating" } },

  // Checking for overlapping edges within the same module
  // Calendar Module
  { data: { source: "calendar", target: "calendar_reminder" } },
  { data: { source: "calendar", target: "calendar_invitation" } },
  { data: { source: "calendar", target: "calendar_task" } },
  { data: { source: "calendar", target: "calendar_meeting" } },
  { data: { source: "calendar", target: "calendar_schedule" } },
  { data: { source: "calendar", target: "calendar_notification" } },
  { data: { source: "calendar", target: "calendar_sync" } },
  { data: { source: "calendar", target: "calendar_share" } },
  { data: { source: "calendar", target: "calendar_settings" } },
  { data: { source: "calendar", target: "calendar_view" } },
  { data: { source: "calendar", target: "calendar_timezone" } },
  { data: { source: "calendar", target: "calendar_attachment" } },
  { data: { source: "calendar", target: "calendar_availability" } },
  { data: { source: "calendar", target: "calendar_event" } },
  { data: { source: "calendar", target: "calendar_event_details" } },
  { data: { source: "calendar", target: "calendar_event_location" } },
  { data: { source: "calendar", target: "calendar_event_participants" } },
  { data: { source: "calendar", target: "calendar_event_notes" } },
  { data: { source: "calendar", target: "calendar_event_status" } },

  // Authorization Module
  { data: { source: "auth_login", target: "auth_logout" } },
  { data: { source: "auth_register", target: "auth_forgot_password" } },
  { data: { source: "auth_reset_password", target: "auth_verify_email" } },
  { data: { source: "auth_two_factor", target: "auth_session" } },
  { data: { source: "auth_token", target: "auth_permission" } },
  { data: { source: "auth_role", target: "auth_user" } },
  { data: { source: "auth_profile", target: "auth_security_question" } },
  { data: { source: "auth_security_answer", target: "auth_activity_log" } },
  { data: { source: "auth_privacy_policy", target: "auth_terms_of_service" } },
  { data: { source: "auth_account_recovery", target: "auth_account_lock" } },

  // Residence Module
  { data: { source: "residence_address", target: "residence_owner" } },
  { data: { source: "residence_tenant", target: "residence_lease" } },
  { data: { source: "residence_rent", target: "residence_maintenance" } },
  { data: { source: "residence_utility", target: "residence_inspection" } },
  { data: { source: "residence_security", target: "residence_parking" } },
  { data: { source: "residence_amenity", target: "residence_policy" } },
  { data: { source: "residence_agreement", target: "residence_payment" } },
  { data: { source: "residence_history", target: "residence_complaint" } },
  { data: { source: "residence_feedback", target: "residence_renewal" } },
  { data: { source: "residence_termination", target: "residence_transfer" } },

  // Recipe Module
  { data: { source: "recipe_ingredients", target: "recipe_instructions" } },
  { data: { source: "recipe_nutrition", target: "recipe_cuisine" } },
  { data: { source: "recipe_diet", target: "recipe_course" } },
  { data: { source: "recipe_cooking_time", target: "recipe_preparation_time" } },
  { data: { source: "recipe_servings", target: "recipe_rating" } },
  { data: { source: "recipe_reviews", target: "recipe_author" } },
  { data: { source: "recipe_source", target: "recipe_tags" } },
  { data: { source: "recipe_image", target: "recipe_video" } },
  { data: { source: "recipe_equipment", target: "recipe_notes" } },
  { data: { source: "recipe_yield", target: "recipe_category" } },

  // Person Module
  { data: { source: "person_name", target: "person_age" } },
  { data: { source: "person_gender", target: "person_address" } },
  { data: { source: "person_email", target: "person_phone" } },
  { data: { source: "person_occupation", target: "person_nationality" } },
  { data: { source: "person_marital_status", target: "person_education" } },
  { data: { source: "person_hobbies", target: "person_social_media" } },
  { data: { source: "person_biography", target: "person_skills" } },
  { data: { source: "person_languages", target: "person_references" } },
  { data: { source: "person_certifications", target: "person_projects" } },
  { data: { source: "person_achievements", target: "person_interests" } },

  // Parking Module
  { data: { source: "parking_lot", target: "parking_meter" } },
  { data: { source: "parking_ticket", target: "parking_garage" } },
  { data: { source: "parking_space", target: "parking_fee" } },
  { data: { source: "parking_reservation", target: "parking_availability" } },
  { data: { source: "parking_duration", target: "parking_location" } },
  { data: { source: "parking_payment", target: "parking_validation" } },
  { data: { source: "parking_violation", target: "parking_permit" } },
  { data: { source: "parking_app", target: "parking_lot" } },

  // Money Module
  { data: { source: "currency_exchange", target: "bank_account" } },
  { data: { source: "credit_card", target: "debit_card" } },
  { data: { source: "loan", target: "mortgage" } },
  { data: { source: "investment", target: "savings" } },
  { data: { source: "checking_account", target: "financial_advisor" } },
  { data: { source: "budgeting", target: "expense_tracking" } },
  { data: { source: "taxes", target: "insurance" } },
  { data: { source: "retirement_plan", target: "wealth_management" } },
  { data: { source: "financial_planning", target: "currency_exchange" } },

  // Payment Module
  { data: { source: "payment_gateway", target: "payment_processor" } },
  { data: { source: "payment_method", target: "payment_transaction" } },
  { data: { source: "payment_confirmation", target: "payment_refund" } },
  { data: { source: "payment_receipt", target: "payment_invoice" } },
  { data: { source: "payment_subscription", target: "payment_security" } },
  { data: { source: "payment_authorization", target: "payment_settlement" } },
  { data: { source: "payment_dispute", target: "payment_fraud_detection" } },
  { data: { source: "payment_gateway_integration", target: "payment_gateway" } },

  // Flight Booking Module
  { data: { source: "flight_search", target: "flight_reservation" } },
  { data: { source: "flight_ticket", target: "flight_schedule" } },
  { data: { source: "flight_status", target: "flight_cancellation" } },
  { data: { source: "flight_checkin", target: "flight_boarding_pass" } },
  { data: { source: "flight_seat_selection", target: "flight_meal_preference" } },
  { data: { source: "flight_baggage", target: "flight_lounge_access" } },
  { data: { source: "flight_rewards", target: "flight_customer_support" } },
  { data: { source: "flight_travel_insurance", target: "flight_booking_confirmation" } },

  // Rating Module
  { data: { source: "rating_system", target: "rating_scale" } },
  { data: { source: "rating_review", target: "rating_feedback" } },
  { data: { source: "rating_average", target: "rating_distribution" } },
  { data: { source: "rating_criteria", target: "rating_submission" } },
  { data: { source: "rating_verification", target: "rating_approval" } },
  { data: { source: "rating_rejection", target: "rating_update" } },
  { data: { source: "rating_deletion", target: "rating_notification" } },
  { data: { source: "rating_summary", target: "rating_system" } },

  // Word Module
  { data: { source: "word_processing", target: "text_analysis" } },
  { data: { source: "text_classification", target: "text_clustering" } },
  { data: { source: "text_summarization", target: "text_translation" } },
  { data: { source: "text_generation", target: "text_recognition" } },
  { data: { source: "text_extraction", target: "text_correction" } },
  { data: { source: "text_segmentation", target: "text_normalization" } },
  { data: { source: "text_tokenization", target: "text_embedding" } },
  { data: { source: "text_similarity", target: "text_parsing" } },
  { data: { source: "text_indexing", target: "text_search" } },
  { data: { source: "text_classification_model", target: "text_clustering_model" } },

  // Email Module
  { data: { source: "inbox", target: "sent" } },
  { data: { source: "drafts", target: "spam" } },
  { data: { source: "trash", target: "compose" } },
  { data: { source: "reply", target: "forward" } },
  { data: { source: "attachments", target: "contacts" } },
  { data: { source: "filters", target: "labels" } },
  { data: { source: "settings", target: "notifications" } },
  { data: { source: "search", target: "archive" } },
  { data: { source: "mark_as_read", target: "mark_as_unread" } },
  { data: { source: "move_to_folder", target: "starred" } },

  // Time Module
  { data: { source: "time_series_analysis", target: "time_forecasting" } },
  { data: { source: "time_classification", target: "time_clustering" } },
  { data: { source: "time_anomaly_detection", target: "time_feature_extraction" } },
  { data: { source: "time_feature_selection", target: "time_dimensionality_reduction" } },
  { data: { source: "time_pattern_recognition", target: "time_signal_processing" } },
  { data: { source: "time_spectral_analysis", target: "time_frequency_analysis" } },
  { data: { source: "time_wavelet_transform", target: "time_trend_analysis" } },
  { data: { source: "time_seasonal_analysis", target: "time_correlation_analysis" } },
  { data: { source: "time_regression_analysis", target: "time_decomposition" } },
  { data: { source: "time_smoothing", target: "time_filtering" } },

  // Image Module
  { data: { source: "image_filtering", target: "image_compression" } },
  { data: { source: "image_restoration", target: "image_fusion" } },
  { data: { source: "image_inpainting", target: "image_recognition" } },
  { data: { source: "image_classification", target: "image_segmentation" } },
  { data: { source: "object_detection", target: "face_recognition" } },
  { data: { source: "image_enhancement", target: "image_generation" } },
  { data: { source: "image_captioning", target: "image_filtering" } },

  // Weather Module
  { data: { source: "barometric_pressure", target: "precipitation_type" } },
  { data: { source: "wind_chill", target: "get_extended_forecast" } },
  { data: { source: "wind_speed", target: "relative_humidity" } },
  { data: { source: "record_low_temperature", target: "wind" } },
  { data: { source: "get_sunrise", target: "pressure_trend" } },
  { data: { source: "snow_fall", target: "day_high_temperature" } },
  { data: { source: "day_low_temperature", target: "low_temperature" } },
  { data: { source: "normal_low_temperature", target: "record_low_temperature" } },

  // Wine Module
  { data: { source: "wine_catalog_section", target: "appellation" } },
  { data: { source: "wine_recommendation", target: "wine_item" } },
  { data: { source: "vine_yard", target: "wine_store" } },
  { data: { source: "wine_catalog", target: "varietal" } },
  { data: { source: "wine_recommendation_description", target: "wine_item_name" } },
  { data: { source: "fine_wine_catalog", target: "vintage_year" } },
  { data: { source: "find_wine_store", target: "wine_search_str" } },
  { data: { source: "find_meal_recommendation_from_wine", target: "wine_catalog_section" } },

  // MEASUREMENT NODES
  { data: { id: "measurement_length", label: "MeasurementLength" } },
  { data: { id: "measurement_width", label: "MeasurementWidth" } },
  { data: { id: "measurement_height", label: "MeasurementHeight" } },
  { data: { id: "measurement_weight", label: "MeasurementWeight" } },
  { data: { id: "measurement_volume", label: "MeasurementVolume" } },
  { data: { id: "measurement_density", label: "MeasurementDensity" } },
  { data: { id: "measurement_temperature", label: "MeasurementTemperature" } },
  { data: { id: "measurement_pressure", label: "MeasurementPressure" } },
  { data: { id: "measurement_speed", label: "MeasurementSpeed" } },
  { data: { id: "measurement_acceleration", label: "MeasurementAcceleration" } },
  { data: { id: "measurement_force", label: "MeasurementForce" } },
  { data: { id: "measurement_energy", label: "MeasurementEnergy" } },
  { data: { id: "measurement_power", label: "MeasurementPower" } },
  { data: { id: "measurement_frequency", label: "MeasurementFrequency" } },
  { data: { id: "measurement_voltage", label: "MeasurementVoltage" } },
  { data: { id: "measurement_current", label: "MeasurementCurrent" } },
  { data: { id: "measurement_resistance", label: "MeasurementResistance" } },
  { data: { id: "measurement_capacitance", label: "MeasurementCapacitance" } },
  { data: { id: "measurement_inductance", label: "MeasurementInductance" } },
  { data: { id: "measurement_impedance", label: "MeasurementImpedance" } },
  // MEASUREMENT EDGES
  { data: { source: "measurement", target: "measurement_length" } },
  { data: { source: "measurement", target: "measurement_width" } },
  { data: { source: "measurement", target: "measurement_height" } },
  { data: { source: "measurement", target: "measurement_weight" } },
  { data: { source: "measurement", target: "measurement_volume" } },
  { data: { source: "measurement", target: "measurement_density" } },
  { data: { source: "measurement", target: "measurement_temperature" } },
  { data: { source: "measurement", target: "measurement_pressure" } },
  { data: { source: "measurement", target: "measurement_speed" } },
  { data: { source: "measurement", target: "measurement_acceleration" } },
  { data: { source: "measurement", target: "measurement_force" } },
  { data: { source: "measurement", target: "measurement_energy" } },
  { data: { source: "measurement", target: "measurement_power" } },
  { data: { source: "measurement", target: "measurement_frequency" } },
  { data: { source: "measurement", target: "measurement_voltage" } },
  { data: { source: "measurement", target: "measurement_current" } },
  { data: { source: "measurement", target: "measurement_resistance" } },
  { data: { source: "measurement", target: "measurement_capacitance" } },
  { data: { source: "measurement", target: "measurement_inductance" } },
  { data: { source: "measurement", target: "measurement_impedance" } },
  // Interconnections
  { data: { source: "measurement_length", target: "measurement_width" } },
  { data: { source: "measurement_length", target: "measurement_height" } },
  { data: { source: "measurement_weight", target: "measurement_volume" } },
  { data: { source: "measurement_temperature", target: "measurement_pressure" } },
  { data: { source: "measurement_voltage", target: "measurement_current" } },
  { data: { source: "measurement_voltage", target: "measurement_resistance" } },
  { data: { source: "measurement_current", target: "measurement_resistance" } },
  { data: { source: "measurement_capacitance", target: "measurement_inductance" } },
  { data: { source: "measurement_impedance", target: "measurement_resistance" } },

  // EARTHQUAKE NODES
  { data: { id: "earthquake_magnitude", label: "EarthquakeMagnitude" } },
  { data: { id: "earthquake_depth", label: "EarthquakeDepth" } },
  { data: { id: "earthquake_location", label: "EarthquakeLocation" } },
  { data: { id: "earthquake_time", label: "EarthquakeTime" } },
  { data: { id: "earthquake_intensity", label: "EarthquakeIntensity" } },
  { data: { id: "earthquake_duration", label: "EarthquakeDuration" } },
  { data: { id: "earthquake_epicenter", label: "EarthquakeEpicenter" } },
  { data: { id: "earthquake_fault", label: "EarthquakeFault" } },
  { data: { id: "earthquake_aftershock", label: "EarthquakeAftershock" } },
  { data: { id: "earthquake_forecast", label: "EarthquakeForecast" } },
  // EARTHQUAKE EDGES
  { data: { source: "earthquake", target: "earthquake_magnitude" } },
  { data: { source: "earthquake", target: "earthquake_depth" } },
  { data: { source: "earthquake", target: "earthquake_location" } },
  { data: { source: "earthquake", target: "earthquake_time" } },
  { data: { source: "earthquake", target: "earthquake_intensity" } },
  { data: { source: "earthquake", target: "earthquake_duration" } },
  { data: { source: "earthquake", target: "earthquake_epicenter" } },
  { data: { source: "earthquake", target: "earthquake_fault" } },
  { data: { source: "earthquake", target: "earthquake_aftershock" } },
  { data: { source: "earthquake", target: "earthquake_forecast" } },
  // EARTHQUAKE INTERCONNECTIONS
  { data: { source: "earthquake_magnitude", target: "earthquake_intensity" } },
  { data: { source: "earthquake_magnitude", target: "earthquake_duration" } },
  { data: { source: "earthquake_depth", target: "earthquake_epicenter" } },
  { data: { source: "earthquake_location", target: "earthquake_epicenter" } },
  { data: { source: "earthquake_time", target: "earthquake_forecast" } },
  { data: { source: "earthquake_intensity", target: "earthquake_aftershock" } },
  { data: { source: "earthquake_duration", target: "earthquake_aftershock" } },
  { data: { source: "earthquake_epicenter", target: "earthquake_fault" } },
  { data: { source: "earthquake_fault", target: "earthquake_aftershock" } },
  { data: { source: "earthquake_forecast", target: "earthquake_aftershock" } },
  // CALENDAR NODES
  { data: { id: "calendar_event", label: "CalendarEvent" } },
  { data: { id: "calendar_reminder", label: "CalendarReminder" } },
  { data: { id: "calendar_invitation", label: "CalendarInvitation" } },
  { data: { id: "calendar_task", label: "CalendarTask" } },
  { data: { id: "calendar_meeting", label: "CalendarMeeting" } },
  { data: { id: "calendar_schedule", label: "CalendarSchedule" } },
  { data: { id: "calendar_notification", label: "CalendarNotification" } },
  { data: { id: "calendar_sync", label: "CalendarSync" } },
  { data: { id: "calendar_share", label: "CalendarShare" } },
  { data: { id: "calendar_settings", label: "CalendarSettings" } },
  { data: { id: "calendar_view", label: "CalendarView" } },
  { data: { id: "calendar_timezone", label: "CalendarTimezone" } },
  { data: { id: "calendar_attachment", label: "CalendarAttachment" } },
  { data: { id: "calendar_recurrence", label: "CalendarRecurrence" } },
  { data: { id: "calendar_availability", label: "CalendarAvailability" } },
  { data: { id: "calendar_event_details", label: "CalendarEventDetails" } },
  { data: { id: "calendar_event_location", label: "CalendarEventLocation" } },
  { data: { id: "calendar_event_participants", label: "CalendarEventParticipants" } },
  { data: { id: "calendar_event_notes", label: "CalendarEventNotes" } },
  { data: { id: "calendar_event_status", label: "CalendarEventStatus" } },
  // CALENDAR EDGES
  { data: { source: "calendar", target: "calendar_event" } },
  { data: { source: "calendar_event", target: "calendar_reminder" } },
  { data: { source: "calendar_event", target: "calendar_invitation" } },
  { data: { source: "calendar_event", target: "calendar_task" } },
  { data: { source: "calendar_event", target: "calendar_meeting" } },
  { data: { source: "calendar_event", target: "calendar_schedule" } },
  { data: { source: "calendar_event", target: "calendar_notification" } },
  { data: { source: "calendar_event", target: "calendar_sync" } },
  { data: { source: "calendar_event", target: "calendar_share" } },
  { data: { source: "calendar_event", target: "calendar_settings" } },
  { data: { source: "calendar_event", target: "calendar_view" } },
  { data: { source: "calendar_event", target: "calendar_timezone" } },
  { data: { source: "calendar_event", target: "calendar_attachment" } },
  { data: { source: "calendar_event", target: "calendar_recurrence" } },
  { data: { source: "calendar_event", target: "calendar_availability" } },
  { data: { source: "calendar_event", target: "calendar_event_details" } },
  { data: { source: "calendar_event", target: "calendar_event_location" } },
  { data: { source: "calendar_event", target: "calendar_event_participants" } },
  { data: { source: "calendar_event", target: "calendar_event_notes" } },
  { data: { source: "calendar_event", target: "calendar_event_status" } },

  // RESTAURANT NODES
  { data: { id: "restaurant_menu", label: "RestaurantMenu" } },
  { data: { id: "restaurant_reservation", label: "RestaurantReservation" } },
  { data: { id: "restaurant_order", label: "RestaurantOrder" } },
  { data: { id: "restaurant_review", label: "RestaurantReview" } },
  { data: { id: "restaurant_rating", label: "RestaurantRating" } },
  { data: { id: "restaurant_location", label: "RestaurantLocation" } },
  { data: { id: "restaurant_cuisine", label: "RestaurantCuisine" } },
  { data: { id: "restaurant_hours", label: "RestaurantHours" } },
  { data: { id: "restaurant_contact", label: "RestaurantContact" } },
  { data: { id: "restaurant_payment", label: "RestaurantPayment" } },
  { data: { id: "restaurant_specials", label: "RestaurantSpecials" } },
  { data: { id: "restaurant_events", label: "RestaurantEvents" } },
  { data: { id: "restaurant_staff", label: "RestaurantStaff" } },
  { data: { id: "restaurant_chef", label: "RestaurantChef" } },
  { data: { id: "restaurant_ambiance", label: "RestaurantAmbiance" } },
  { data: { id: "restaurant_parking", label: "RestaurantParking" } },
  { data: { id: "restaurant_delivery", label: "RestaurantDelivery" } },
  { data: { id: "restaurant_takeout", label: "RestaurantTakeout" } },
  { data: { id: "restaurant_loyalty_program", label: "RestaurantLoyaltyProgram" } },
  { data: { id: "restaurant_menu_item", label: "RestaurantMenuItem" } },

  // RESTAURANT EDGES
  { data: { source: "restaurant", target: "restaurant_menu" } },
  { data: { source: "restaurant", target: "restaurant_reservation" } },
  { data: { source: "restaurant", target: "restaurant_order" } },
  { data: { source: "restaurant", target: "restaurant_review" } },
  { data: { source: "restaurant", target: "restaurant_rating" } },
  { data: { source: "restaurant", target: "restaurant_location" } },
  { data: { source: "restaurant", target: "restaurant_cuisine" } },
  { data: { source: "restaurant", target: "restaurant_hours" } },
  { data: { source: "restaurant", target: "restaurant_contact" } },
  { data: { source: "restaurant", target: "restaurant_payment" } },
  { data: { source: "restaurant", target: "restaurant_specials" } },
  { data: { source: "restaurant", target: "restaurant_events" } },
  { data: { source: "restaurant", target: "restaurant_staff" } },
  { data: { source: "restaurant", target: "restaurant_chef" } },
  { data: { source: "restaurant", target: "restaurant_ambiance" } },
  { data: { source: "restaurant", target: "restaurant_parking" } },
  { data: { source: "restaurant", target: "restaurant_delivery" } },
  { data: { source: "restaurant", target: "restaurant_takeout" } },
  { data: { source: "restaurant", target: "restaurant_loyalty_program" } },
  { data: { source: "restaurant_menu", target: "restaurant_menu_item" } },

  // RESTAURANT INTERCONNECTIONS
  { data: { source: "restaurant_menu", target: "restaurant_specials" } },
  { data: { source: "restaurant_reservation", target: "restaurant_events" } },
  { data: { source: "restaurant_order", target: "restaurant_payment" } },
  { data: { source: "restaurant_review", target: "restaurant_rating" } },
  { data: { source: "restaurant_location", target: "restaurant_parking" } },
  { data: { source: "restaurant_cuisine", target: "restaurant_menu_item" } },
  { data: { source: "restaurant_hours", target: "restaurant_events" } },
  { data: { source: "restaurant_contact", target: "restaurant_loyalty_program" } },
  { data: { source: "restaurant_staff", target: "restaurant_chef" } },
  { data: { source: "restaurant_delivery", target: "restaurant_takeout" } },

  // COMIC STRIP NODES
  { data: { id: "comic_strip_character", label: "ComicStripCharacter" } },
  { data: { id: "comic_strip_storyline", label: "ComicStripStoryline" } },
  { data: { id: "comic_strip_panel", label: "ComicStripPanel" } },
  { data: { id: "comic_strip_dialogue", label: "ComicStripDialogue" } },
  { data: { id: "comic_strip_artwork", label: "ComicStripArtwork" } },
  { data: { id: "comic_strip_background", label: "ComicStripBackground" } },
  { data: { id: "comic_strip_color", label: "ComicStripColor" } },
  { data: { id: "comic_strip_ink", label: "ComicStripInk" } },
  { data: { id: "comic_strip_pencil", label: "ComicStripPencil" } },
  { data: { id: "comic_strip_lettering", label: "ComicStripLettering" } },
  { data: { id: "comic_strip_sound_effects", label: "ComicStripSoundEffects" } },
  { data: { id: "comic_strip_narration", label: "ComicStripNarration" } },
  { data: { id: "comic_strip_theme", label: "ComicStripTheme" } },
  { data: { id: "comic_strip_genre", label: "ComicStripGenre" } },
  { data: { id: "comic_strip_publication", label: "ComicStripPublication" } },
  { data: { id: "comic_strip_author", label: "ComicStripAuthor" } },
  { data: { id: "comic_strip_illustrator", label: "ComicStripIllustrator" } },
  { data: { id: "comic_strip_editor", label: "ComicStripEditor" } },
  { data: { id: "comic_strip_publisher", label: "ComicStripPublisher" } },
  { data: { id: "comic_strip_release_date", label: "ComicStripReleaseDate" } },
  { data: { id: "comic_strip_series", label: "ComicStripSeries" } },
  { data: { id: "comic_strip_issue", label: "ComicStripIssue" } },
  { data: { id: "comic_strip_cover", label: "ComicStripCover" } },
  { data: { id: "comic_strip_adaptation", label: "ComicStripAdaptation" } },
  { data: { id: "comic_strip_merchandise", label: "ComicStripMerchandise" } },

  // COMIC STRIP EDGES
  { data: { source: "comic_strip", target: "comic_strip_character" } },
  { data: { source: "comic_strip", target: "comic_strip_storyline" } },
  { data: { source: "comic_strip", target: "comic_strip_panel" } },
  { data: { source: "comic_strip", target: "comic_strip_dialogue" } },
  { data: { source: "comic_strip", target: "comic_strip_artwork" } },
  { data: { source: "comic_strip", target: "comic_strip_background" } },
  { data: { source: "comic_strip", target: "comic_strip_color" } },
  { data: { source: "comic_strip", target: "comic_strip_ink" } },
  { data: { source: "comic_strip", target: "comic_strip_pencil" } },
  { data: { source: "comic_strip", target: "comic_strip_lettering" } },
  { data: { source: "comic_strip", target: "comic_strip_sound_effects" } },
  { data: { source: "comic_strip", target: "comic_strip_narration" } },
  { data: { source: "comic_strip", target: "comic_strip_theme" } },
  { data: { source: "comic_strip", target: "comic_strip_genre" } },
  { data: { source: "comic_strip", target: "comic_strip_publication" } },
  { data: { source: "comic_strip", target: "comic_strip_author" } },
  { data: { source: "comic_strip", target: "comic_strip_illustrator" } },
  { data: { source: "comic_strip", target: "comic_strip_editor" } },
  { data: { source: "comic_strip", target: "comic_strip_publisher" } },
  { data: { source: "comic_strip", target: "comic_strip_release_date" } },
  { data: { source: "comic_strip", target: "comic_strip_series" } },
  { data: { source: "comic_strip", target: "comic_strip_issue" } },
  { data: { source: "comic_strip", target: "comic_strip_cover" } },
  { data: { source: "comic_strip", target: "comic_strip_adaptation" } },
  { data: { source: "comic_strip", target: "comic_strip_merchandise" } },

  // COMIC STRIP INTERCONNECTIONS
  { data: { source: "comic_strip_character", target: "comic_strip_storyline" } },
  { data: { source: "comic_strip_panel", target: "comic_strip_dialogue" } },
  { data: { source: "comic_strip_artwork", target: "comic_strip_background" } },
  { data: { source: "comic_strip_color", target: "comic_strip_ink" } },
  { data: { source: "comic_strip_pencil", target: "comic_strip_lettering" } },
  { data: { source: "comic_strip_sound_effects", target: "comic_strip_narration" } },
  { data: { source: "comic_strip_theme", target: "comic_strip_genre" } },
  { data: { source: "comic_strip_publication", target: "comic_strip_release_date" } },
  { data: { source: "comic_strip_series", target: "comic_strip_issue" } },
  { data: { source: "comic_strip_cover", target: "comic_strip_adaptation" } },
  { data: { source: "comic_strip_merchandise", target: "comic_strip_adaptation" } },

  // AUTHORIZATION NODES
  { data: { id: "auth_login", label: "AuthLogin" } },
  { data: { id: "auth_logout", label: "AuthLogout" } },
  { data: { id: "auth_register", label: "AuthRegister" } },
  { data: { id: "auth_forgot_password", label: "AuthForgotPassword" } },
  { data: { id: "auth_reset_password", label: "AuthResetPassword" } },
  { data: { id: "auth_verify_email", label: "AuthVerifyEmail" } },
  { data: { id: "auth_two_factor", label: "AuthTwoFactor" } },
  { data: { id: "auth_session", label: "AuthSession" } },
  { data: { id: "auth_token", label: "AuthToken" } },
  { data: { id: "auth_permission", label: "AuthPermission" } },
  { data: { id: "auth_role", label: "AuthRole" } },
  { data: { id: "auth_user", label: "AuthUser" } },
  { data: { id: "auth_profile", label: "AuthProfile" } },
  { data: { id: "auth_security_question", label: "AuthSecurityQuestion" } },
  { data: { id: "auth_security_answer", label: "AuthSecurityAnswer" } },
  { data: { id: "auth_activity_log", label: "AuthActivityLog" } },
  { data: { id: "auth_privacy_policy", label: "AuthPrivacyPolicy" } },
  { data: { id: "auth_terms_of_service", label: "AuthTermsOfService" } },
  { data: { id: "auth_account_recovery", label: "AuthAccountRecovery" } },
  { data: { id: "auth_account_lock", label: "AuthAccountLock" } },
  // AUTHORIZATION EDGES
  { data: { source: "authorization", target: "auth_login" } },
  { data: { source: "authorization", target: "auth_logout" } },
  { data: { source: "authorization", target: "auth_register" } },
  { data: { source: "authorization", target: "auth_forgot_password" } },
  { data: { source: "authorization", target: "auth_reset_password" } },
  { data: { source: "authorization", target: "auth_verify_email" } },
  { data: { source: "authorization", target: "auth_two_factor" } },
  { data: { source: "authorization", target: "auth_session" } },
  { data: { source: "authorization", target: "auth_token" } },
  { data: { source: "authorization", target: "auth_permission" } },
  { data: { source: "authorization", target: "auth_role" } },
  { data: { source: "authorization", target: "auth_user" } },
  { data: { source: "authorization", target: "auth_profile" } },
  { data: { source: "authorization", target: "auth_security_question" } },
  { data: { source: "authorization", target: "auth_security_answer" } },
  { data: { source: "authorization", target: "auth_activity_log" } },
  { data: { source: "authorization", target: "auth_privacy_policy" } },
  { data: { source: "authorization", target: "auth_terms_of_service" } },
  { data: { source: "authorization", target: "auth_account_recovery" } },
  { data: { source: "authorization", target: "auth_account_lock" } },

  // RESIDENCE NODES
  { data: { id: "residence_address", label: "ResidenceAddress" } },
  { data: { id: "residence_owner", label: "ResidenceOwner" } },
  { data: { id: "residence_tenant", label: "ResidenceTenant" } },
  { data: { id: "residence_lease", label: "ResidenceLease" } },
  { data: { id: "residence_rent", label: "ResidenceRent" } },
  { data: { id: "residence_maintenance", label: "ResidenceMaintenance" } },
  { data: { id: "residence_utility", label: "ResidenceUtility" } },
  { data: { id: "residence_inspection", label: "ResidenceInspection" } },
  { data: { id: "residence_security", label: "ResidenceSecurity" } },
  { data: { id: "residence_parking", label: "ResidenceParking" } },
  { data: { id: "residence_amenity", label: "ResidenceAmenity" } },
  { data: { id: "residence_policy", label: "ResidencePolicy" } },
  { data: { id: "residence_agreement", label: "ResidenceAgreement" } },
  { data: { id: "residence_payment", label: "ResidencePayment" } },
  { data: { id: "residence_history", label: "ResidenceHistory" } },
  { data: { id: "residence_complaint", label: "ResidenceComplaint" } },
  { data: { id: "residence_feedback", label: "ResidenceFeedback" } },
  { data: { id: "residence_renewal", label: "ResidenceRenewal" } },
  { data: { id: "residence_termination", label: "ResidenceTermination" } },
  { data: { id: "residence_transfer", label: "ResidenceTransfer" } },
  // RESIDENCE EDGES
  { data: { source: "residence", target: "residence_address" } },
  { data: { source: "residence", target: "residence_owner" } },
  { data: { source: "residence", target: "residence_tenant" } },
  { data: { source: "residence", target: "residence_lease" } },
  { data: { source: "residence", target: "residence_rent" } },
  { data: { source: "residence", target: "residence_maintenance" } },
  { data: { source: "residence", target: "residence_utility" } },
  { data: { source: "residence", target: "residence_inspection" } },
  { data: { source: "residence", target: "residence_security" } },
  { data: { source: "residence", target: "residence_parking" } },
  { data: { source: "residence", target: "residence_amenity" } },
  { data: { source: "residence", target: "residence_policy" } },
  { data: { source: "residence", target: "residence_agreement" } },
  { data: { source: "residence", target: "residence_payment" } },
  { data: { source: "residence", target: "residence_history" } },
  { data: { source: "residence", target: "residence_complaint" } },
  { data: { source: "residence", target: "residence_feedback" } },
  { data: { source: "residence", target: "residence_renewal" } },
  { data: { source: "residence", target: "residence_termination" } },
  { data: { source: "residence", target: "residence_transfer" } },

  // RECIPE NODES
  { data: { id: "recipe_ingredients", label: "RecipeIngredients" } },
  { data: { id: "recipe_instructions", label: "RecipeInstructions" } },
  { data: { id: "recipe_nutrition", label: "RecipeNutrition" } },
  { data: { id: "recipe_cuisine", label: "RecipeCuisine" } },
  { data: { id: "recipe_diet", label: "RecipeDiet" } },
  { data: { id: "recipe_course", label: "RecipeCourse" } },
  { data: { id: "recipe_cooking_time", label: "RecipeCookingTime" } },
  { data: { id: "recipe_preparation_time", label: "RecipePreparationTime" } },
  { data: { id: "recipe_servings", label: "RecipeServings" } },
  { data: { id: "recipe_rating", label: "RecipeRating" } },
  { data: { id: "recipe_reviews", label: "RecipeReviews" } },
  { data: { id: "recipe_author", label: "RecipeAuthor" } },
  { data: { id: "recipe_source", label: "RecipeSource" } },
  { data: { id: "recipe_tags", label: "RecipeTags" } },
  { data: { id: "recipe_image", label: "RecipeImage" } },
  { data: { id: "recipe_video", label: "RecipeVideo" } },
  { data: { id: "recipe_equipment", label: "RecipeEquipment" } },
  { data: { id: "recipe_notes", label: "RecipeNotes" } },
  { data: { id: "recipe_yield", label: "RecipeYield" } },
  { data: { id: "recipe_category", label: "RecipeCategory" } },
  // RECIPE EDGES
  { data: { source: "recipe", target: "recipe_ingredients" } },
  { data: { source: "recipe", target: "recipe_instructions" } },
  { data: { source: "recipe", target: "recipe_nutrition" } },
  { data: { source: "recipe", target: "recipe_cuisine" } },
  { data: { source: "recipe", target: "recipe_diet" } },
  { data: { source: "recipe", target: "recipe_course" } },
  { data: { source: "recipe", target: "recipe_cooking_time" } },
  { data: { source: "recipe", target: "recipe_preparation_time" } },
  { data: { source: "recipe", target: "recipe_servings" } },
  { data: { source: "recipe", target: "recipe_rating" } },
  { data: { source: "recipe", target: "recipe_reviews" } },
  { data: { source: "recipe", target: "recipe_author" } },
  { data: { source: "recipe", target: "recipe_source" } },
  { data: { source: "recipe", target: "recipe_tags" } },
  { data: { source: "recipe", target: "recipe_image" } },
  { data: { source: "recipe", target: "recipe_video" } },
  { data: { source: "recipe", target: "recipe_equipment" } },
  { data: { source: "recipe", target: "recipe_notes" } },
  { data: { source: "recipe", target: "recipe_yield" } },
  { data: { source: "recipe", target: "recipe_category" } },

  // PERSON NODES
  { data: { id: "person_name", label: "PersonName" } },
  { data: { id: "person_age", label: "PersonAge" } },
  { data: { id: "person_gender", label: "PersonGender" } },
  { data: { id: "person_address", label: "PersonAddress" } },
  { data: { id: "person_email", label: "PersonEmail" } },
  { data: { id: "person_phone", label: "PersonPhone" } },
  { data: { id: "person_occupation", label: "PersonOccupation" } },
  { data: { id: "person_nationality", label: "PersonNationality" } },
  { data: { id: "person_marital_status", label: "PersonMaritalStatus" } },
  { data: { id: "person_education", label: "PersonEducation" } },
  { data: { id: "person_hobbies", label: "PersonHobbies" } },
  { data: { id: "person_social_media", label: "PersonSocialMedia" } },
  { data: { id: "person_biography", label: "PersonBiography" } },
  { data: { id: "person_skills", label: "PersonSkills" } },
  { data: { id: "person_languages", label: "PersonLanguages" } },
  { data: { id: "person_references", label: "PersonReferences" } },
  { data: { id: "person_certifications", label: "PersonCertifications" } },
  { data: { id: "person_projects", label: "PersonProjects" } },
  { data: { id: "person_achievements", label: "PersonAchievements" } },
  { data: { id: "person_interests", label: "PersonInterests" } },
  // PERSON EDGES
  { data: { source: "person", target: "person_name" } },
  { data: { source: "person", target: "person_age" } },
  { data: { source: "person", target: "person_gender" } },
  { data: { source: "person", target: "person_address" } },
  { data: { source: "person", target: "person_email" } },
  { data: { source: "person", target: "person_phone" } },
  { data: { source: "person", target: "person_occupation" } },
  { data: { source: "person", target: "person_nationality" } },
  { data: { source: "person", target: "person_marital_status" } },
  { data: { source: "person", target: "person_education" } },
  { data: { source: "person", target: "person_hobbies" } },
  { data: { source: "person", target: "person_social_media" } },
  { data: { source: "person", target: "person_biography" } },
  { data: { source: "person", target: "person_skills" } },
  { data: { source: "person", target: "person_languages" } },
  { data: { source: "person", target: "person_references" } },
  { data: { source: "person", target: "person_certifications" } },
  { data: { source: "person", target: "person_projects" } },
  { data: { source: "person", target: "person_achievements" } },
  { data: { source: "person", target: "person_interests" } },

  // PARKING NODES
  { data: { id: "parking_lot", label: "ParkingLot" } },
  { data: { id: "parking_meter", label: "ParkingMeter" } },
  { data: { id: "parking_ticket", label: "ParkingTicket" } },
  { data: { id: "parking_garage", label: "ParkingGarage" } },
  { data: { id: "parking_space", label: "ParkingSpace" } },
  { data: { id: "parking_fee", label: "ParkingFee" } },
  { data: { id: "parking_reservation", label: "ParkingReservation" } },
  { data: { id: "parking_availability", label: "ParkingAvailability" } },
  { data: { id: "parking_duration", label: "ParkingDuration" } },
  { data: { id: "parking_location", label: "ParkingLocation" } },
  { data: { id: "parking_payment", label: "ParkingPayment" } },
  { data: { id: "parking_validation", label: "ParkingValidation" } },
  { data: { id: "parking_violation", label: "ParkingViolation" } },
  { data: { id: "parking_permit", label: "ParkingPermit" } },
  { data: { id: "parking_app", label: "ParkingApp" } },
  // PARKING EDGES
  { data: { source: "parking", target: "parking_lot" } },
  { data: { source: "parking", target: "parking_meter" } },
  { data: { source: "parking", target: "parking_ticket" } },
  { data: { source: "parking", target: "parking_garage" } },
  { data: { source: "parking", target: "parking_space" } },
  { data: { source: "parking", target: "parking_fee" } },
  { data: { source: "parking", target: "parking_reservation" } },
  { data: { source: "parking", target: "parking_availability" } },
  { data: { source: "parking", target: "parking_duration" } },
  { data: { source: "parking", target: "parking_location" } },
  { data: { source: "parking", target: "parking_payment" } },
  { data: { source: "parking", target: "parking_validation" } },
  { data: { source: "parking", target: "parking_violation" } },
  { data: { source: "parking", target: "parking_permit" } },
  { data: { source: "parking", target: "parking_app" } },

  // MONEY NODES
  { data: { id: "currency_exchange", label: "CurrencyExchange" } },
  { data: { id: "bank_account", label: "BankAccount" } },
  { data: { id: "credit_card", label: "CreditCard" } },
  { data: { id: "debit_card", label: "DebitCard" } },
  { data: { id: "loan", label: "Loan" } },
  { data: { id: "mortgage", label: "Mortgage" } },
  { data: { id: "investment", label: "Investment" } },
  { data: { id: "savings", label: "Savings" } },
  { data: { id: "checking_account", label: "CheckingAccount" } },
  { data: { id: "financial_advisor", label: "FinancialAdvisor" } },
  { data: { id: "budgeting", label: "Budgeting" } },
  { data: { id: "expense_tracking", label: "ExpenseTracking" } },
  { data: { id: "taxes", label: "Taxes" } },
  { data: { id: "insurance", label: "Insurance" } },
  { data: { id: "retirement_plan", label: "RetirementPlan" } },
  { data: { id: "wealth_management", label: "WealthManagement" } },
  { data: { id: "financial_planning", label: "FinancialPlanning" } },
  // MONEY EDGES
  { data: { source: "money", target: "currency_exchange" } },
  { data: { source: "money", target: "bank_account" } },
  { data: { source: "money", target: "credit_card" } },
  { data: { source: "money", target: "debit_card" } },
  { data: { source: "money", target: "loan" } },
  { data: { source: "money", target: "mortgage" } },
  { data: { source: "money", target: "investment" } },
  { data: { source: "money", target: "savings" } },
  { data: { source: "money", target: "checking_account" } },
  { data: { source: "money", target: "financial_advisor" } },
  { data: { source: "money", target: "budgeting" } },
  { data: { source: "money", target: "expense_tracking" } },
  { data: { source: "money", target: "taxes" } },
  { data: { source: "money", target: "insurance" } },
  { data: { source: "money", target: "retirement_plan" } },
  { data: { source: "money", target: "wealth_management" } },
  { data: { source: "money", target: "financial_planning" } },

  // PAYMENT NODES
  { data: { id: "payment_gateway", label: "PaymentGateway" } },
  { data: { id: "payment_processor", label: "PaymentProcessor" } },
  { data: { id: "payment_method", label: "PaymentMethod" } },
  { data: { id: "payment_transaction", label: "PaymentTransaction" } },
  { data: { id: "payment_confirmation", label: "PaymentConfirmation" } },
  { data: { id: "payment_refund", label: "PaymentRefund" } },
  { data: { id: "payment_receipt", label: "PaymentReceipt" } },
  { data: { id: "payment_invoice", label: "PaymentInvoice" } },
  { data: { id: "payment_subscription", label: "PaymentSubscription" } },
  { data: { id: "payment_security", label: "PaymentSecurity" } },
  { data: { id: "payment_authorization", label: "PaymentAuthorization" } },
  { data: { id: "payment_settlement", label: "PaymentSettlement" } },
  { data: { id: "payment_dispute", label: "PaymentDispute" } },
  { data: { id: "payment_fraud_detection", label: "PaymentFraudDetection" } },
  { data: { id: "payment_gateway_integration", label: "PaymentGatewayIntegration" } },
  // PAYMENT EDGES
  { data: { source: "payment", target: "payment_gateway" } },
  { data: { source: "payment", target: "payment_processor" } },
  { data: { source: "payment", target: "payment_method" } },
  { data: { source: "payment", target: "payment_transaction" } },
  { data: { source: "payment", target: "payment_confirmation" } },
  { data: { source: "payment", target: "payment_refund" } },
  { data: { source: "payment", target: "payment_receipt" } },
  { data: { source: "payment", target: "payment_invoice" } },
  { data: { source: "payment", target: "payment_subscription" } },
  { data: { source: "payment", target: "payment_security" } },
  { data: { source: "payment", target: "payment_authorization" } },
  { data: { source: "payment", target: "payment_settlement" } },
  { data: { source: "payment", target: "payment_dispute" } },
  { data: { source: "payment", target: "payment_fraud_detection" } },
  { data: { source: "payment", target: "payment_gateway_integration" } },

  // FLIGHT BOOKING NODES
  { data: { id: "flight_search", label: "FlightSearch" } },
  { data: { id: "flight_reservation", label: "FlightReservation" } },
  { data: { id: "flight_ticket", label: "FlightTicket" } },
  { data: { id: "flight_schedule", label: "FlightSchedule" } },
  { data: { id: "flight_status", label: "FlightStatus" } },
  { data: { id: "flight_cancellation", label: "FlightCancellation" } },
  { data: { id: "flight_checkin", label: "FlightCheckin" } },
  { data: { id: "flight_boarding_pass", label: "FlightBoardingPass" } },
  { data: { id: "flight_seat_selection", label: "FlightSeatSelection" } },
  { data: { id: "flight_meal_preference", label: "FlightMealPreference" } },
  { data: { id: "flight_baggage", label: "FlightBaggage" } },
  { data: { id: "flight_lounge_access", label: "FlightLoungeAccess" } },
  { data: { id: "flight_rewards", label: "FlightRewards" } },
  { data: { id: "flight_customer_support", label: "FlightCustomerSupport" } },
  { data: { id: "flight_travel_insurance", label: "FlightTravelInsurance" } },
  { data: { id: "flight_booking_confirmation", label: "FlightBookingConfirmation" } },
  // FLIGHT BOOKING EDGES
  { data: { source: "flight_booking", target: "flight_search" } },
  { data: { source: "flight_booking", target: "flight_reservation" } },
  { data: { source: "flight_booking", target: "flight_ticket" } },
  { data: { source: "flight_booking", target: "flight_schedule" } },
  { data: { source: "flight_booking", target: "flight_status" } },
  { data: { source: "flight_booking", target: "flight_cancellation" } },
  { data: { source: "flight_booking", target: "flight_checkin" } },
  { data: { source: "flight_booking", target: "flight_boarding_pass" } },
  { data: { source: "flight_booking", target: "flight_seat_selection" } },
  { data: { source: "flight_booking", target: "flight_meal_preference" } },
  { data: { source: "flight_booking", target: "flight_baggage" } },
  { data: { source: "flight_booking", target: "flight_lounge_access" } },
  { data: { source: "flight_booking", target: "flight_rewards" } },
  { data: { source: "flight_booking", target: "flight_customer_support" } },
  { data: { source: "flight_booking", target: "flight_travel_insurance" } },
  { data: { source: "flight_booking", target: "flight_booking_confirmation" } },

  // RATING NODES
  { data: { id: "rating_system", label: "RatingSystem" } },
  { data: { id: "rating_scale", label: "RatingScale" } },
  { data: { id: "rating_review", label: "RatingReview" } },
  { data: { id: "rating_feedback", label: "RatingFeedback" } },
  { data: { id: "rating_average", label: "RatingAverage" } },
  { data: { id: "rating_distribution", label: "RatingDistribution" } },
  { data: { id: "rating_criteria", label: "RatingCriteria" } },
  { data: { id: "rating_submission", label: "RatingSubmission" } },
  { data: { id: "rating_verification", label: "RatingVerification" } },
  { data: { id: "rating_approval", label: "RatingApproval" } },
  { data: { id: "rating_rejection", label: "RatingRejection" } },
  { data: { id: "rating_update", label: "RatingUpdate" } },
  { data: { id: "rating_deletion", label: "RatingDeletion" } },
  { data: { id: "rating_notification", label: "RatingNotification" } },
  { data: { id: "rating_summary", label: "RatingSummary" } },
  // RATING EDGES
  { data: { source: "rating", target: "rating_system" } },
  { data: { source: "rating", target: "rating_scale" } },
  { data: { source: "rating", target: "rating_review" } },
  { data: { source: "rating", target: "rating_feedback" } },
  { data: { source: "rating", target: "rating_average" } },
  { data: { source: "rating", target: "rating_distribution" } },
  { data: { source: "rating", target: "rating_criteria" } },
  { data: { source: "rating", target: "rating_submission" } },
  { data: { source: "rating", target: "rating_verification" } },
  { data: { source: "rating", target: "rating_approval" } },
  { data: { source: "rating", target: "rating_rejection" } },
  { data: { source: "rating", target: "rating_update" } },
  { data: { source: "rating", target: "rating_deletion" } },
  { data: { source: "rating", target: "rating_notification" } },
  { data: { source: "rating", target: "rating_summary" } },

  // WORD NODES
  { data: { id: "word_processing", label: "WordProcessing" } },
  { data: { id: "text_analysis", label: "TextAnalysis" } },
  { data: { id: "text_classification", label: "TextClassification" } },
  { data: { id: "text_clustering", label: "TextClustering" } },
  { data: { id: "text_summarization", label: "TextSummarization" } },
  { data: { id: "text_translation", label: "TextTranslation" } },
  { data: { id: "text_generation", label: "TextGeneration" } },
  { data: { id: "text_recognition", label: "TextRecognition" } },
  { data: { id: "text_extraction", label: "TextExtraction" } },
  { data: { id: "text_correction", label: "TextCorrection" } },
  { data: { id: "text_segmentation", label: "TextSegmentation" } },
  { data: { id: "text_normalization", label: "TextNormalization" } },
  { data: { id: "text_tokenization", label: "TextTokenization" } },
  { data: { id: "text_embedding", label: "TextEmbedding" } },
  { data: { id: "text_similarity", label: "TextSimilarity" } },
  { data: { id: "text_parsing", label: "TextParsing" } },
  { data: { id: "text_indexing", label: "TextIndexing" } },
  { data: { id: "text_search", label: "TextSearch" } },
  { data: { id: "text_classification_model", label: "TextClassificationModel" } },
  { data: { id: "text_clustering_model", label: "TextClusteringModel" } },

  // WORD EDGES
  { data: { source: "word", target: "word_processing" } },
  { data: { source: "word", target: "text_analysis" } },
  { data: { source: "word", target: "text_classification" } },
  { data: { source: "word", target: "text_clustering" } },
  { data: { source: "word", target: "text_summarization" } },
  { data: { source: "word", target: "text_translation" } },
  { data: { source: "word", target: "text_generation" } },
  { data: { source: "word", target: "text_recognition" } },
  { data: { source: "word", target: "text_extraction" } },
  { data: { source: "word", target: "text_correction" } },
  { data: { source: "word", target: "text_segmentation" } },
  { data: { source: "word", target: "text_normalization" } },
  { data: { source: "word", target: "text_tokenization" } },
  { data: { source: "word", target: "text_embedding" } },
  { data: { source: "word", target: "text_similarity" } },
  { data: { source: "word", target: "text_parsing" } },
  { data: { source: "word", target: "text_indexing" } },
  { data: { source: "word", target: "text_search" } },
  { data: { source: "text_classification", target: "text_classification_model" } },
  { data: { source: "text_clustering", target: "text_clustering_model" } },

  // EMAIL NODES
  { data: { id: "inbox", label: "Inbox" } },
  { data: { id: "sent", label: "Sent" } },
  { data: { id: "drafts", label: "Drafts" } },
  { data: { id: "spam", label: "Spam" } },
  { data: { id: "trash", label: "Trash" } },
  { data: { id: "compose", label: "Compose" } },
  { data: { id: "reply", label: "Reply" } },
  { data: { id: "forward", label: "Forward" } },
  { data: { id: "attachments", label: "Attachments" } },
  { data: { id: "contacts", label: "Contacts" } },
  { data: { id: "filters", label: "Filters" } },
  { data: { id: "labels", label: "Labels" } },
  { data: { id: "settings", label: "Settings" } },
  { data: { id: "notifications", label: "Notifications" } },
  { data: { id: "search", label: "Search" } },
  { data: { id: "archive", label: "Archive" } },
  { data: { id: "mark_as_read", label: "MarkAsRead" } },
  { data: { id: "mark_as_unread", label: "MarkAsUnread" } },
  { data: { id: "move_to_folder", label: "MoveToFolder" } },
  { data: { id: "starred", label: "Starred" } },
  // EMAIL EDGES
  { data: { source: "email", target: "inbox" } },
  { data: { source: "email", target: "sent" } },
  { data: { source: "email", target: "drafts" } },
  { data: { source: "email", target: "spam" } },
  { data: { source: "email", target: "trash" } },
  { data: { source: "email", target: "compose" } },
  { data: { source: "email", target: "reply" } },
  { data: { source: "email", target: "forward" } },
  { data: { source: "email", target: "attachments" } },
  { data: { source: "email", target: "contacts" } },
  { data: { source: "email", target: "filters" } },
  { data: { source: "email", target: "labels" } },
  { data: { source: "email", target: "settings" } },
  { data: { source: "email", target: "notifications" } },
  { data: { source: "email", target: "search" } },
  { data: { source: "email", target: "archive" } },
  { data: { source: "email", target: "mark_as_read" } },
  { data: { source: "email", target: "mark_as_unread" } },
  { data: { source: "email", target: "move_to_folder" } },
  { data: { source: "email", target: "starred" } },

  // TIME NODES
  { data: { id: "time_series_analysis", label: "TimeSeriesAnalysis" } },
  { data: { id: "time_forecasting", label: "TimeForecasting" } },
  { data: { id: "time_classification", label: "TimeClassification" } },
  { data: { id: "time_clustering", label: "TimeClustering" } },
  { data: { id: "time_anomaly_detection", label: "TimeAnomalyDetection" } },
  { data: { id: "time_feature_extraction", label: "TimeFeatureExtraction" } },
  { data: { id: "time_feature_selection", label: "TimeFeatureSelection" } },
  { data: { id: "time_dimensionality_reduction", label: "TimeDimensionalityReduction" } },
  { data: { id: "time_pattern_recognition", label: "TimePatternRecognition" } },
  { data: { id: "time_signal_processing", label: "TimeSignalProcessing" } },
  { data: { id: "time_spectral_analysis", label: "TimeSpectralAnalysis" } },
  { data: { id: "time_frequency_analysis", label: "TimeFrequencyAnalysis" } },
  { data: { id: "time_wavelet_transform", label: "TimeWaveletTransform" } },
  { data: { id: "time_trend_analysis", label: "TimeTrendAnalysis" } },
  { data: { id: "time_seasonal_analysis", label: "TimeSeasonalAnalysis" } },
  { data: { id: "time_correlation_analysis", label: "TimeCorrelationAnalysis" } },
  { data: { id: "time_regression_analysis", label: "TimeRegressionAnalysis" } },
  { data: { id: "time_decomposition", label: "TimeDecomposition" } },
  { data: { id: "time_smoothing", label: "TimeSmoothing" } },
  { data: { id: "time_filtering", label: "TimeFiltering" } },
  // TIME EDGES
  { data: { source: "time", target: "time_series_analysis" } },
  { data: { source: "time", target: "time_forecasting" } },
  { data: { source: "time", target: "time_classification" } },
  { data: { source: "time", target: "time_clustering" } },
  { data: { source: "time", target: "time_anomaly_detection" } },
  { data: { source: "time", target: "time_feature_extraction" } },
  { data: { source: "time", target: "time_feature_selection" } },
  { data: { source: "time", target: "time_dimensionality_reduction" } },
  { data: { source: "time", target: "time_pattern_recognition" } },
  { data: { source: "time", target: "time_signal_processing" } },
  { data: { source: "time", target: "time_spectral_analysis" } },
  { data: { source: "time", target: "time_frequency_analysis" } },
  { data: { source: "time", target: "time_wavelet_transform" } },
  { data: { source: "time", target: "time_trend_analysis" } },
  { data: { source: "time", target: "time_seasonal_analysis" } },
  { data: { source: "time", target: "time_correlation_analysis" } },
  { data: { source: "time", target: "time_regression_analysis" } },
  { data: { source: "time", target: "time_decomposition" } },
  { data: { source: "time", target: "time_smoothing" } },
  { data: { source: "time", target: "time_filtering" } },

  // IMAGE NODES
  { data: { id: "image_filtering", label: "ImageFiltering" } },
  { data: { id: "image_compression", label: "ImageCompression" } },
  { data: { id: "image_restoration", label: "ImageRestoration" } },
  { data: { id: "image_fusion", label: "ImageFusion" } },
  { data: { id: "image_inpainting", label: "ImageInpainting" } },
  { data: { id: "image_recognition", label: "ImageRecognition" } },
  { data: { id: "image_classification", label: "ImageClassification" } },
  { data: { id: "image_segmentation", label: "ImageSegmentation" } },
  { data: { id: "object_detection", label: "ObjectDetection" } },
  { data: { id: "face_recognition", label: "FaceRecognition" } },
  { data: { id: "image_enhancement", label: "ImageEnhancement" } },
  { data: { id: "image_generation", label: "ImageGeneration" } },
  { data: { id: "image_captioning", label: "ImageCaptioning" } },

  // IMAGE EDGES
  { data: { source: "image", target: "image_recognition" } },
  { data: { source: "image", target: "image_classification" } },
  { data: { source: "image", target: "image_segmentation" } },
  { data: { source: "image", target: "object_detection" } },
  { data: { source: "image", target: "face_recognition" } },
  { data: { source: "image", target: "image_enhancement" } },
  { data: { source: "image", target: "image_generation" } },
  { data: { source: "image", target: "image_captioning" } },
  { data: { source: "image", target: "image_filtering" } },
  { data: { source: "image", target: "image_compression" } },
  { data: { source: "image", target: "image_restoration" } },
  { data: { source: "image", target: "image_fusion" } },
  { data: { source: "image", target: "image_inpainting" } },

  // WEATHER NODES
  { data: { id: "barometric_pressure", label: "BarometicPressure" } },
  { data: { id: "precipitation_type", label: "PrecipitationType" } },
  { data: { id: "wind_chill", label: "WindChill" } },
  { data: { id: "get_extended_forecast", label: "GetExtendedForecast" } },
  { data: { id: "wind_speed", label: "WindSpeed" } },
  { data: { id: "relative_humidity", label: "RelativeHumidity" } },
  { data: { id: "record_low_temperature", label: "RecordLowTemperature" } },
  { data: { id: "wind", label: "Wind" } },
  { data: { id: "get_sunrise", label: "GetSunrise" } },
  { data: { id: "pressure_trend", label: "PressureTrend" } },
  { data: { id: "snow_fall", label: "SnowFall" } },
  { data: { id: "day_high_temperature", label: "DayHighTemperature" } },
  { data: { id: "day_low_temperature", label: "DayLowTemperature" } },
  { data: { id: "low_temperature", label: "LowTemperature" } },
  { data: { id: "normal_low_temperature", label: "NormalLowTemperature" } },
  // WEATHER EDGES
  { data: { source: "weather", target: "barometric_pressure" } },
  { data: { source: "weather", target: "precipitation_type" } },
  { data: { source: "weather", target: "wind_chill" } },
  { data: { source: "weather", target: "get_extended_forecast" } },
  { data: { source: "weather", target: "relative_humidity" } },
  { data: { source: "weather", target: "record_low_temperature" } },
  { data: { source: "weather", target: "wind" } },
  { data: { source: "weather", target: "get_sunrise" } },
  { data: { source: "weather", target: "pressure_trend" } },
  { data: { source: "weather", target: "snow_fall" } },
  { data: { source: "weather", target: "wind_speed" } },
  { data: { source: "wind", target: "wind_speed" } },
  { data: { source: "weather", target: "day_high_temperature" } },
  { data: { source: "weather", target: "day_low_temperature" } },
  { data: { source: "weather", target: "low_temperature" } },
  { data: { source: "low_temperature", target: "record_low_temperature" } },
  { data: { source: "low_temperature", target: "normal_low_temperature" } },
  { data: { source: "weather", target: "normal_low_temperature" } },

  // WINE NODES
  { data: { id: "wine_catalog_section", label: "WineCatalogSection" } },
  { data: { id: "appellation", label: "Appellation" } },
  { data: { id: "wine_recommendation", label: "WineRecommendation" } },
  { data: { id: "wine_item", label: "WineItem" } },
  { data: { id: "vine_yard", label: "Vineyard" } },
  { data: { id: "wine_store", label: "WineStore" } },
  { data: { id: "wine_catalog", label: "WineCatalog" } },
  { data: { id: "varietal", label: "Varietal" } },
  { data: { id: "wine_recommendation_description", label: "WineRecommendationDescription" } },
  { data: { id: "wine_item_name", label: "WineItemName" } },
  { data: { id: "fine_wine_catalog", label: "FindWineCatalog" } },
  { data: { id: "vintage_year", label: "VintageYear" } },
  { data: { id: "find_wine_store", label: "FindWineStore" } },
  { data: { id: "wine_search_str", label: "WineSearchStr" } },
  { data: { id: "find_meal_recommendation_from_wine", label: "FindMealRecommendationFromWine" } },

  // WINE EDGES
  { data: { source: "wine", target: "wine_catalog_section" } },
  { data: { source: "wine", target: "appellation" } },
  { data: { source: "wine", target: "wine_recommendation" } },
  { data: { source: "wine", target: "wine_item" } },
  { data: { source: "wine", target: "vine_yard" } },
  { data: { source: "wine", target: "wine_store" } },
  { data: { source: "wine", target: "wine_catalog" } },
  { data: { source: "wine", target: "varietal" } },
  { data: { source: "wine", target: "wine_recommendation_description" } },
  { data: { source: "wine", target: "wine_item_name" } },
  { data: { source: "wine", target: "fine_wine_catalog" } },
  { data: { source: "wine", target: "vintage_year" } },
  { data: { source: "wine", target: "find_wine_store" } },
  { data: { source: "wine", target: "wine_search_str" } },
  { data: { source: "wine", target: "find_meal_recommendation_from_wine" } },
];

export default elements;
